[workspace]
resolver = "2"
members = [
    "hooklib",
    "polyhook",
    "sgd"
]

[workspace.dependencies]
petgraph = { version = "0.6.5" }
glam = { version = "0.29.0", features = ["bytemuck"] }
rhai = { version = "1.19.0" }
