[package]
name = "sgd"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = { workspace = true }
glam = { workspace = true }
rand = { version = "0.8.5", features = ["small_rng"] }
itertools = "0.13.0"

[dev-dependencies]
hooklib = { path = "../hooklib" }
