[package]
name = "hooklib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.5"
uuid = { version = "1.10.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
