[package]
name = "polyhook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
egui = "0.28.1"
env_logger = "0.11.5"
pollster = "0.3.0"
wgpu = "22.1.0"
winit = "0.30.5"

